"""empty message

Revision ID: 775b316e4546
Revises: 8da00c8299e2
Create Date: 2021-06-17 20:16:03.806525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775b316e4546'
down_revision = '8da00c8299e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'credentials_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('credentials_id', sa.VARCHAR(length=150), nullable=False))
    # ### end Alembic commands ###
