"""empty message

Revision ID: 83f4a47d0912
Revises: 199b5dc29e90
Create Date: 2021-08-08 20:11:44.259462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f4a47d0912'
down_revision = '199b5dc29e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(length=80), nullable=True),
    sa.Column('address_line2', sa.String(length=80), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('muncipality_id', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(length=80), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('price_of_service', sa.Float(), nullable=False),
    sa.Column('services_provided', sa.Integer(), nullable=True),
    sa.Column('five_stars', sa.Integer(), nullable=True),
    sa.Column('four_starts', sa.Integer(), nullable=True),
    sa.Column('three_starts', sa.Integer(), nullable=True),
    sa.Column('two_starts', sa.Integer(), nullable=True),
    sa.Column('one_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('org')
    op.drop_table('address')
    # ### end Alembic commands ###
