"""empty message

Revision ID: 8da00c8299e2
Revises: ccf3233ef092
Create Date: 2021-06-17 20:01:30.025515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da00c8299e2'
down_revision = 'ccf3233ef092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('second_name', sa.String(length=150), nullable=False),
    sa.Column('first_surname', sa.String(length=150), nullable=False),
    sa.Column('second_surname', sa.String(length=150), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('home_number', sa.String(length=15), nullable=True),
    sa.Column('office_number', sa.String(length=15), nullable=True),
    sa.Column('facebook_profile', sa.String(length=150), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=150), nullable=True),
    sa.Column('twitter_profile', sa.String(length=150), nullable=True),
    sa.Column('id_image', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('credentials_id', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
