# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address_id: int=None, street: str=None, outer_number: str=None, inner_number: str=None, neighborhood_id: int=None, muncipality_id: int=None, zip_code: str=None, state_id: int=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param address_id: The address_id of this Address.  # noqa: E501
        :type address_id: int
        :param street: The street of this Address.  # noqa: E501
        :type street: str
        :param outer_number: The outer_number of this Address.  # noqa: E501
        :type outer_number: str
        :param inner_number: The inner_number of this Address.  # noqa: E501
        :type inner_number: str
        :param neighborhood_id: The neighborhood_id of this Address.  # noqa: E501
        :type neighborhood_id: int
        :param muncipality_id: The muncipality_id of this Address.  # noqa: E501
        :type muncipality_id: int
        :param zip_code: The zip_code of this Address.  # noqa: E501
        :type zip_code: str
        :param state_id: The state_id of this Address.  # noqa: E501
        :type state_id: int
        """
        self.swagger_types = {
            'address_id': int,
            'street': str,
            'outer_number': str,
            'inner_number': str,
            'neighborhood_id': int,
            'muncipality_id': int,
            'zip_code': str,
            'state_id': int
        }

        self.attribute_map = {
            'address_id': 'addressId',
            'street': 'street',
            'outer_number': 'outerNumber',
            'inner_number': 'innerNumber',
            'neighborhood_id': 'neighborhoodId',
            'muncipality_id': 'muncipalityId',
            'zip_code': 'zipCode',
            'state_id': 'stateId'
        }
        self._address_id = address_id
        self._street = street
        self._outer_number = outer_number
        self._inner_number = inner_number
        self._neighborhood_id = neighborhood_id
        self._muncipality_id = muncipality_id
        self._zip_code = zip_code
        self._state_id = state_id

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_id(self) -> int:
        """Gets the address_id of this Address.

        Unique id  # noqa: E501

        :return: The address_id of this Address.
        :rtype: int
        """
        return self._address_id

    @address_id.setter
    def address_id(self, address_id: int):
        """Sets the address_id of this Address.

        Unique id  # noqa: E501

        :param address_id: The address_id of this Address.
        :type address_id: int
        """
        if address_id is None:
            raise ValueError("Invalid value for `address_id`, must not be `None`")  # noqa: E501

        self._address_id = address_id

    @property
    def street(self) -> str:
        """Gets the street of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :return: The street of this Address.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :param street: The street of this Address.
        :type street: str
        """
        if street is None:
            raise ValueError("Invalid value for `street`, must not be `None`")  # noqa: E501

        self._street = street

    @property
    def outer_number(self) -> str:
        """Gets the outer_number of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :return: The outer_number of this Address.
        :rtype: str
        """
        return self.outer_number

    @outer_number.setter
    def outer_number(self, outer_number: str):
        """Sets the outer_number of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :param outer_number: The outer_number of this Address.
        :type outer_number: str
        """

        self._outer_number = outer_number

    @property
    def inner_number(self) -> str:
        """Gets the inner_number of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :return: The inner_number of this Address.
        :rtype: str
        """
        return self.inner_number

    @inner_number.setter
    def inner_number(self, inner_number: str):
        """Sets the inner_number of this Address.

        Suite/Apartment, Outer Number, Street  # noqa: E501

        :param inner_number: The inner_number of this Address.
        :type inner_number: str
        """

        self._inner_number = inner_number

    @property
    def neighborhood_id(self) -> int:
        """Gets the neighborhood_id of this Address.

        Colony or Neighborhood  # noqa: E501

        :return: The neighborhood_id of this Address.
        :rtype: int
        """
        return self._neighborhood_id

    @neighborhood_id.setter
    def neighborhood_id(self, neighborhood_id: int):
        """Sets the neighborhood_id of this Address.

        Colony or Neighborhood  # noqa: E501

        :param neighborhood_id: The neighborhood_id of this Address.
        :type neighborhood_id: int
        """
        if neighborhood_id is None:
            raise ValueError("Invalid value for `neighborhood_id`, must not be `None`")  # noqa: E501

        self._neighborhood_id = neighborhood_id

    @property
    def muncipality_id(self) -> int:
        """Gets the muncipality_id of this Address.

        Muncipality  # noqa: E501

        :return: The muncipality_id of this Address.
        :rtype: int
        """
        return self._muncipality_id

    @muncipality_id.setter
    def muncipality_id(self, muncipality_id: int):
        """Sets the muncipality_id of this Address.

        Muncipality  # noqa: E501

        :param muncipality_id: The muncipality_id of this Address.
        :type muncipality_id: int
        """
        if muncipality_id is None:
            raise ValueError("Invalid value for `muncipality_id`, must not be `None`")  # noqa: E501

        self._muncipality_id = muncipality_id

    @property
    def zip_code(self) -> str:
        """Gets the zip_code of this Address.

        Zipcode  # noqa: E501

        :return: The zip_code of this Address.
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: str):
        """Sets the zip_code of this Address.

        Zipcode  # noqa: E501

        :param zip_code: The zip_code of this Address.
        :type zip_code: str
        """
        if zip_code is None:
            raise ValueError("Invalid value for `zip_code`, must not be `None`")  # noqa: E501

        self._zip_code = zip_code

    @property
    def state_id(self) -> int:
        """Gets the state_id of this Address.

        Foreign key for State  # noqa: E501

        :return: The state_id of this Address.
        :rtype: int
        """
        return self._state_id

    @state_id.setter
    def state_id(self, state_id: int):
        """Sets the state_id of this Address.

        Foreign key for State  # noqa: E501

        :param state_id: The state_id of this Address.
        :type state_id: int
        """
        if state_id is None:
            raise ValueError("Invalid value for `state_id`, must not be `None`")  # noqa: E501

        self._state_id = state_id
