# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class Country(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, country_id: int=None, name: str=None):  # noqa: E501
        """Country - a model defined in Swagger

        :param country_id: The country_id of this Country.  # noqa: E501
        :type country_id: int
        :param name: The name of this Country.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'country_id': int,
            'name': str
        }

        self.attribute_map = {
            'country_id': 'countryId',
            'name': 'name'
        }
        self._country_id = country_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def country_id(self) -> int:
        """Gets the country_id of this Country.


        :return: The country_id of this Country.
        :rtype: int
        """
        return self._country_id

    @country_id.setter
    def country_id(self, country_id: int):
        """Sets the country_id of this Country.


        :param country_id: The country_id of this Country.
        :type country_id: int
        """
        if country_id is None:
            raise ValueError("Invalid value for `country_id`, must not be `None`")  # noqa: E501

        self._country_id = country_id

    @property
    def name(self) -> str:
        """Gets the name of this Country.


        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Country.


        :param name: The name of this Country.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
