# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class Neighbourhood(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, neighbourhood_id: int=None, name: str=None, zip_code: int=None, municipality_id: int=None):  # noqa: E501
        """Neighbourhood - a model defined in Swagger

        :param neighbourhood_id: The neighbourhood_id of this Neighbourhood.  # noqa: E501
        :type neighbourhood_id: int
        :param name: The name of this Neighbourhood.  # noqa: E501
        :type name: str
        :param zip_code: The zip_code of this Neighbourhood.  # noqa: E501
        :type zip_code: int
        :param municipality_id: The municipality_id of this Neighbourhood.  # noqa: E501
        :type municipality_id: int
        """
        self.swagger_types = {
            'neighbourhood_id': int,
            'name': str,
            'zip_code': int,
            'municipality_id': int
        }

        self.attribute_map = {
            'neighbourhood_id': 'neighbourhoodId',
            'name': 'name',
            'zip_code': 'zipCode',
            'municipality_id': 'municipalityId'
        }
        self._neighbourhood_id = neighbourhood_id
        self._name = name
        self._zip_code = zip_code
        self._municipality_id = municipality_id

    @classmethod
    def from_dict(cls, dikt) -> 'Neighbourhood':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Neighbourhood of this Neighbourhood.  # noqa: E501
        :rtype: Neighbourhood
        """
        return util.deserialize_model(dikt, cls)

    @property
    def neighbourhood_id(self) -> int:
        """Gets the neighbourhood_id of this Neighbourhood.


        :return: The neighbourhood_id of this Neighbourhood.
        :rtype: int
        """
        return self._neighbourhood_id

    @neighbourhood_id.setter
    def neighbourhood_id(self, neighbourhood_id: int):
        """Sets the neighbourhood_id of this Neighbourhood.


        :param neighbourhood_id: The neighbourhood_id of this Neighbourhood.
        :type neighbourhood_id: int
        """
        if neighbourhood_id is None:
            raise ValueError("Invalid value for `neighbourhood_id`, must not be `None`")  # noqa: E501

        self._neighbourhood_id = neighbourhood_id

    @property
    def name(self) -> str:
        """Gets the name of this Neighbourhood.


        :return: The name of this Neighbourhood.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Neighbourhood.


        :param name: The name of this Neighbourhood.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def zip_code(self) -> int:
        """Gets the zip_code of this Neighbourhood.


        :return: The zip_code of this Neighbourhood.
        :rtype: int
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code: int):
        """Sets the zip_code of this Neighbourhood.


        :param zip_code: The zip_code of this Neighbourhood.
        :type zip_code: int
        """
        if zip_code is None:
            raise ValueError("Invalid value for `zip_code`, must not be `None`")  # noqa: E501

        self._zip_code = zip_code

    @property
    def municipality_id(self) -> int:
        """Gets the municipality_id of this Neighbourhood.


        :return: The municipality_id of this Neighbourhood.
        :rtype: int
        """
        return self._municipality_id

    @municipality_id.setter
    def municipality_id(self, municipality_id: int):
        """Sets the municipality_id of this Neighbourhood.


        :param municipality_id: The municipality_id of this Neighbourhood.
        :type municipality_id: int
        """
        if municipality_id is None:
            raise ValueError("Invalid value for `municipality_id`, must not be `None`")  # noqa: E501

        self._municipality_id = municipality_id
