# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class NotificationType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_type_id: int=None, notification_type: str=None):  # noqa: E501
        """NotificationType - a model defined in Swagger

        :param notification_type_id: The notification_type_id of this NotificationType.  # noqa: E501
        :type notification_type_id: int
        :param notification_type: The notification_type of this NotificationType.  # noqa: E501
        :type notification_type: str
        """
        self.swagger_types = {
            'notification_type_id': int,
            'notification_type': str
        }

        self.attribute_map = {
            'notification_type_id': 'notificationTypeId',
            'notification_type': 'notificationType'
        }
        self._notification_type_id = notification_type_id
        self._notification_type = notification_type

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationType of this NotificationType.  # noqa: E501
        :rtype: NotificationType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type_id(self) -> int:
        """Gets the notification_type_id of this NotificationType.

        Primary key  # noqa: E501

        :return: The notification_type_id of this NotificationType.
        :rtype: int
        """
        return self._notification_type_id

    @notification_type_id.setter
    def notification_type_id(self, notification_type_id: int):
        """Sets the notification_type_id of this NotificationType.

        Primary key  # noqa: E501

        :param notification_type_id: The notification_type_id of this NotificationType.
        :type notification_type_id: int
        """

        self._notification_type_id = notification_type_id

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this NotificationType.

        Type of notification  # noqa: E501

        :return: The notification_type of this NotificationType.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this NotificationType.

        Type of notification  # noqa: E501

        :param notification_type: The notification_type of this NotificationType.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type
