# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class Service(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_id: int=None, user_id: int=None, category_id: int=None, description: str=None, cost: str=None, created: date=None, last_updated: str=None, status_id: int=None):  # noqa: E501
        """Service - a model defined in Swagger

        :param service_id: The service_id of this Service.  # noqa: E501
        :type service_id: int
        :param user_id: The user_id of this Service.  # noqa: E501
        :type user_id: int
        :param category_id: The category_id of this Service.  # noqa: E501
        :type category_id: int
        :param description: The description of this Service.  # noqa: E501
        :type description: str
        :param cost: The cost of this Service.  # noqa: E501
        :type cost: str
        :param created: The created of this Service.  # noqa: E501
        :type created: date
        :param last_updated: The last_updated of this Service.  # noqa: E501
        :type last_updated: str
        :param status_id: The status_id of this Service.  # noqa: E501
        :type status_id: int
        """
        self.swagger_types = {
            'service_id': int,
            'user_id': int,
            'category_id': int,
            'description': str,
            'cost': str,
            'created': date,
            'last_updated': str,
            'status_id': int
        }

        self.attribute_map = {
            'service_id': 'serviceId',
            'user_id': 'userId',
            'category_id': 'categoryId',
            'description': 'description',
            'cost': 'cost',
            'created': 'created',
            'last_updated': 'lastUpdated',
            'status_id': 'statusId'
        }
        self._service_id = service_id
        self._user_id = user_id
        self._category_id = category_id
        self._description = description
        self._cost = cost
        self._created = created
        self._last_updated = last_updated
        self._status_id = status_id

    @classmethod
    def from_dict(cls, dikt) -> 'Service':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Service of this Service.  # noqa: E501
        :rtype: Service
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_id(self) -> int:
        """Gets the service_id of this Service.

        Primary key  # noqa: E501

        :return: The service_id of this Service.
        :rtype: int
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id: int):
        """Sets the service_id of this Service.

        Primary key  # noqa: E501

        :param service_id: The service_id of this Service.
        :type service_id: int
        """
        if service_id is None:
            raise ValueError("Invalid value for `service_id`, must not be `None`")  # noqa: E501

        self._service_id = service_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Service.

        Foreign key of the account that is associated to this Service  # noqa: E501

        :return: The user_id of this Service.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Service.

        Foreign key of the account that is associated to this Service  # noqa: E501

        :param user_id: The user_id of this Service.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def category_id(self) -> int:
        """Gets the category_id of this Service.

        Foreign key of the category that is associated to this service  # noqa: E501

        :return: The category_id of this Service.
        :rtype: int
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: int):
        """Sets the category_id of this Service.

        Foreign key of the category that is associated to this service  # noqa: E501

        :param category_id: The category_id of this Service.
        :type category_id: int
        """
        if category_id is None:
            raise ValueError("Invalid value for `category_id`, must not be `None`")  # noqa: E501

        self._category_id = category_id

    @property
    def description(self) -> str:
        """Gets the description of this Service.

        Description of the entry  # noqa: E501

        :return: The description of this Service.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Service.

        Description of the entry  # noqa: E501

        :param description: The description of this Service.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def cost(self) -> str:
        """Gets the cost of this Service.

        Cost of the service  # noqa: E501

        :return: The cost of this Service.
        :rtype: str
        """
        return self._cost

    @cost.setter
    def cost(self, cost: str):
        """Sets the cost of this Service.

        Cost of the service  # noqa: E501

        :param cost: The cost of this Service.
        :type cost: str
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")  # noqa: E501

        self._cost = cost

    @property
    def created(self) -> date:
        """Gets the created of this Service.

        Date when catalog entry was created  # noqa: E501

        :return: The created of this Service.
        :rtype: date
        """
        return self._created

    @created.setter
    def created(self, created: date):
        """Sets the created of this Service.

        Date when catalog entry was created  # noqa: E501

        :param created: The created of this Service.
        :type created: date
        """

        self._created = created

    @property
    def last_updated(self) -> str:
        """Gets the last_updated of this Service.

        Date when the catalog entry was updated  # noqa: E501

        :return: The last_updated of this Service.
        :rtype: str
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: str):
        """Sets the last_updated of this Service.

        Date when the catalog entry was updated  # noqa: E501

        :param last_updated: The last_updated of this Service.
        :type last_updated: str
        """

        self._last_updated = last_updated

    @property
    def status_id(self) -> int:
        """Gets the status_id of this Service.

        Foreign key of the status tha is associated to this catalog  # noqa: E501

        :return: The status_id of this Service.
        :rtype: int
        """
        return self._status_id

    @status_id.setter
    def status_id(self, status_id: int):
        """Sets the status_id of this Service.

        Foreign key of the status tha is associated to this catalog  # noqa: E501

        :param status_id: The status_id of this Service.
        :type status_id: int
        """

        self._status_id = status_id
