# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jobbing.models.base_model_ import Model
from jobbing import util


class Skill(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, provider_id: int=None, category_id: int=None, years_of_experience: int=None, price_of_service: float=None, description: str=None, work_zone: str=None, services_provided: int=None, five_stars: int=None, four_starts: int=None, three_starts: int=None, two_starts: int=None, one_start: int=None):  # noqa: E501
        """Skill - a model defined in Swagger

        :param provider_id: The provider_id of this Skill.  # noqa: E501
        :type provider_id: int
        :param category_id: The category_id of this Skill.  # noqa: E501
        :type category_id: int
        :param years_of_experience: The years_of_experience of this Skill.  # noqa: E501
        :type years_of_experience: int
        :param price_of_service: The price_of_service of this Skill.  # noqa: E501
        :type price_of_service: float
        :param description: Description of the message.  # noqa: E501
        :type description: str
        :param work_zone: Zone where the provider works.  # noqa: E501
        :type work_zone: str
        :param services_provided: The services_provided of this Skill.  # noqa: E501
        :type services_provided: int
        :param five_stars: The five_stars of this Skill.  # noqa: E501
        :type five_stars: int
        :param four_starts: The four_starts of this Skill.  # noqa: E501
        :type four_starts: int
        :param three_starts: The three_starts of this Skill.  # noqa: E501
        :type three_starts: int
        :param two_starts: The two_starts of this Skill.  # noqa: E501
        :type two_starts: int
        :param one_start: The one_start of this Skill.  # noqa: E501
        :type one_start: int
        """
        self.swagger_types = {
            'provider_id': int,
            'category_id': int,
            'years_of_experience': int,
            'price_of_service': float,
            'description': str,
            'work_zone': str,
            'services_provided': int,
            'five_stars': int,
            'four_starts': int,
            'three_starts': int,
            'two_starts': int,
            'one_start': int
        }

        self.attribute_map = {
            'provider_id': 'providerId',
            'category_id': 'categoryId',
            'years_of_experience': 'yearsOfExperience',
            'price_of_service': 'priceOfService',
            'description': 'description',
            'work_zone': 'workZone',
            'services_provided': 'servicesProvided',
            'five_stars': 'fiveStars',
            'four_starts': 'fourStarts',
            'three_starts': 'threeStarts',
            'two_starts': 'twoStarts',
            'one_start': 'oneStart'
        }
        self._provider_id = provider_id
        self._category_id = category_id
        self._years_of_experience = years_of_experience
        self._price_of_service = price_of_service
        self._description = description
        self._work_zone = work_zone
        self._services_provided = services_provided
        self._five_stars = five_stars
        self._four_starts = four_starts
        self._three_starts = three_starts
        self._two_starts = two_starts
        self._one_start = one_start

    @classmethod
    def from_dict(cls, dikt) -> 'Skill':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Skill of this Skill.  # noqa: E501
        :rtype: Skill
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider_id(self) -> int:
        """Gets the provider_id of this Skill.

        id of the provider  # noqa: E501

        :return: The provider_id of this Skill.
        :rtype: int
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id: int):
        """Sets the provider_id of this Skill.

        id of the provider  # noqa: E501

        :param provider_id: The provider_id of this Skill.
        :type provider_id: int
        """
        if provider_id is None:
            raise ValueError("Invalid value for `provider_id`, must not be `None`")  # noqa: E501

        self._provider_id = provider_id

    @property
    def category_id(self) -> int:
        """Gets the category_id of this Skill.

        Id of the category  # noqa: E501

        :return: The category_id of this Skill.
        :rtype: int
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: int):
        """Sets the category_id of this Skill.

        Id of the category  # noqa: E501

        :param category_id: The category_id of this Skill.
        :type category_id: int
        """
        if category_id is None:
            raise ValueError("Invalid value for `category_id`, must not be `None`")  # noqa: E501

        self._category_id = category_id

    @property
    def years_of_experience(self) -> int:
        """Gets the years_of_experience of this Skill.

        Years supplying this service  # noqa: E501

        :return: The years_of_experience of this Skill.
        :rtype: int
        """
        return self._years_of_experience

    @years_of_experience.setter
    def years_of_experience(self, years_of_experience: int):
        """Sets the years_of_experience of this Skill.

        Years supplying this service  # noqa: E501

        :param years_of_experience: The years_of_experience of this Skill.
        :type years_of_experience: int
        """
        if years_of_experience is None:
            raise ValueError("Invalid value for `years_of_experience`, must not be `None`")  # noqa: E501

        self._years_of_experience = years_of_experience

    @property
    def price_of_service(self) -> float:
        """Gets the price_of_service of this Skill.

        Price per hour (to be defined)  # noqa: E501

        :return: The price_of_service of this Skill.
        :rtype: float
        """
        return self._price_of_service

    @price_of_service.setter
    def price_of_service(self, price_of_service: float):
        """Sets the price_of_service of this Skill.

        Price per hour (to be defined)  # noqa: E501

        :param price_of_service: The price_of_service of this Skill.
        :type price_of_service: float
        """
        if price_of_service is None:
            raise ValueError("Invalid value for `price_of_service`, must not be `None`")  # noqa: E501

        self._price_of_service = price_of_service

    @property
    def description(self) -> str:
        """Gets the description of this Skill.

        Body of the Message  # noqa: E501

        :return: The description of this Message.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Message.

        Body of the Message  # noqa: E501

        :param description: The description of this Message.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def work_zone(self) -> str:
        """Gets the work_zone of this Skill.

        Body of the Message  # noqa: E501

        :return: The work_zone of this Message.
        :rtype: str
        """
        return self._work_zone

    @work_zone.setter
    def work_zone(self, work_zone: str):
        """Sets the work_zone of this Message.

        Body of the Message  # noqa: E501

        :param work_zone: The work_zone of this Message.
        :type work_zone: str
        """
        if work_zone is None:
            raise ValueError("Invalid value for `work_zone`, must not be `None`")  # noqa: E501

        self._work_zone = work_zone

    @property
    def services_provided(self) -> int:
        """Gets the services_provided of this Skill.

        Total number of services provided on this platform  # noqa: E501

        :return: The services_provided of this Skill.
        :rtype: int
        """
        return self._services_provided

    @services_provided.setter
    def services_provided(self, services_provided: int):
        """Sets the services_provided of this Skill.

        Total number of services provided on this platform  # noqa: E501

        :param services_provided: The services_provided of this Skill.
        :type services_provided: int
        """

        self._services_provided = services_provided

    @property
    def five_stars(self) -> int:
        """Gets the five_stars of this Skill.

        Number of services qualified with 5 star  # noqa: E501

        :return: The five_stars of this Skill.
        :rtype: int
        """
        return self._five_stars

    @five_stars.setter
    def five_stars(self, five_stars: int):
        """Sets the five_stars of this Skill.

        Number of services qualified with 5 star  # noqa: E501

        :param five_stars: The five_stars of this Skill.
        :type five_stars: int
        """

        self._five_stars = five_stars

    @property
    def four_starts(self) -> int:
        """Gets the four_starts of this Skill.

        Number of services qualified with 4 star  # noqa: E501

        :return: The four_starts of this Skill.
        :rtype: int
        """
        return self._four_starts

    @four_starts.setter
    def four_starts(self, four_starts: int):
        """Sets the four_starts of this Skill.

        Number of services qualified with 4 star  # noqa: E501

        :param four_starts: The four_starts of this Skill.
        :type four_starts: int
        """

        self._four_starts = four_starts

    @property
    def three_starts(self) -> int:
        """Gets the three_starts of this Skill.

        Number of services qualified with 3 star  # noqa: E501

        :return: The three_starts of this Skill.
        :rtype: int
        """
        return self._three_starts

    @three_starts.setter
    def three_starts(self, three_starts: int):
        """Sets the three_starts of this Skill.

        Number of services qualified with 3 star  # noqa: E501

        :param three_starts: The three_starts of this Skill.
        :type three_starts: int
        """

        self._three_starts = three_starts

    @property
    def two_starts(self) -> int:
        """Gets the two_starts of this Skill.

        Number of services qualified with 2 star  # noqa: E501

        :return: The two_starts of this Skill.
        :rtype: int
        """
        return self._two_starts

    @two_starts.setter
    def two_starts(self, two_starts: int):
        """Sets the two_starts of this Skill.

        Number of services qualified with 2 star  # noqa: E501

        :param two_starts: The two_starts of this Skill.
        :type two_starts: int
        """

        self._two_starts = two_starts

    @property
    def one_start(self) -> int:
        """Gets the one_start of this Skill.

        Number of services qualified with 1 star  # noqa: E501

        :return: The one_start of this Skill.
        :rtype: int
        """
        return self._one_start

    @one_start.setter
    def one_start(self, one_start: int):
        """Sets the one_start of this Skill.

        Number of services qualified with 1 star  # noqa: E501

        :param one_start: The one_start of this Skill.
        :type one_start: int
        """

        self._one_start = one_start
